Installer: Refine download checks

diff --git a/src/holoinstall b/src/holoinstall
--- a/src/holoinstall
+++ b/src/holoinstall
@@ -6,7 +6,6 @@ CMD_PACMAN_UPDATE=(/usr/bin/pacman -Sy)
 CPU_VENDOR=$(cat /proc/cpuinfo | grep 'vendor' | uniq | cut -c 13-)
 SYSTEM_LOCALE="${SYSTEM_LOCALE:-en_US.UTF-8 UTF-8}"
 HOLO_INSTALL_DIR="${HOLO_INSTALL_DIR:-/mnt}"
-INSTALLER_UPD_QUERY=$(pacman -Qu | grep holoiso-install-script)
 
 # Internet connectivity check
 wget -q --spider http://github.com
@@ -20,8 +19,11 @@ fi
 # Checking if installer is up to date:
 echo "Checking if installer is up to date..."
 ${CMD_PACMAN_UPDATE}
+echo "Pacman DB update complete... Continuing in 2 seconds..."
+sleep 2
+INSTALLER_UPD_QUERY=$(pacman -Qu | grep holoiso-install-script)
 if [ -n "${INSTALLER_UPD_QUERY}" ]; then
-  pacman -S holoiso-install-script
+  pacman -S --noconfirm holoiso-install-script
   echo "Installer updated. Please run holoinstall again."
   exit
 else
@@ -53,10 +55,28 @@ check_mount(){
 	fi
 }
 
-check_download(){
+check_download_pacstrap(){
 	if [ $1 != 0 ]; then
 		echo "\nError: Something went wrong when $2.\nPlease make sure you have a stable internet connection!\n"
-		exit 1
+		read "Do you want to retry? (y/n) " RESTART_PACSTRAP
+		if [[ "${RESTART_PACSTRAP}" == "y" ]] || [[ "${RESTART_PACSTRAP}" == "Y" ]]; then
+			pacstrap -i ${HOLO_INSTALL_DIR} base base-devel ${UCODE_INSTALL} linux-holoiso linux-holoiso-headers linux-neptune-dri linux-neptune-dri-headers linux-firmware
+		else
+			exit 1
+		fi
+	fi
+}
+
+check_download_deck(){
+	if [ $1 != 0 ]; then
+		echo "\nError: Something went wrong when $2.\nPlease make sure you have a stable internet connection!\n"
+		read "Do you want to retry? (y/n) " RESTART_DECK
+		if [[ "${RESTART_DECK}" == "y" ]] || [[ "${RESTART_DECK}" == "Y" ]]; then
+			arch-chroot ${HOLO_INSTALL_DIR} ${CMD_PACMAN_UPDATE}
+			arch-chroot ${HOLO_INSTALL_DIR} ${CMD_PACMAN_INSTALL} holoiso-main holoiso-updateclient wireplumber
+		else
+			exit 1
+		fi
 	fi
 }
 
@@ -208,7 +228,7 @@ base_os_install() {
 	${CMD_MOUNT_BOOT}
 	check_mount $? boot
 	pacstrap -i ${HOLO_INSTALL_DIR} base base-devel ${UCODE_INSTALL} linux-holoiso linux-holoiso-headers linux-neptune-dri linux-neptune-dri-headers linux-firmware
-	check_download $? "installing base package"
+	check_download_pacstrap $? "installing base package"
 	echo "Pacstrap complete. Rebuilding kernel modules."
 	sleep 2
 	arch-chroot ${HOLO_INSTALL_DIR} depmod -a $(ls /lib/modules)
@@ -289,7 +309,7 @@ full_install() {
     # The actual installation begins here:
 	arch-chroot ${HOLO_INSTALL_DIR} ${CMD_PACMAN_UPDATE}
 	arch-chroot ${HOLO_INSTALL_DIR} ${CMD_PACMAN_INSTALL} holoiso-main holoiso-updateclient wireplumber
-	check_download $? "installing full SteamOS 3"
+	check_download_deck $? "installing full SteamOS 3"
 	sleep 1
 	while true
 	do
@@ -324,8 +344,6 @@ full_install() {
 	mkdir ${HOLO_INSTALL_DIR}/etc/sddm.conf.d
 	echo "[General]\nDisplayServer=wayland\n\n[Autologin]\nUser=${HOLOUSER}\nSession=gamescope-wayland.desktop" >> ${HOLO_INSTALL_DIR}/etc/sddm.conf.d/autologin.conf
 	mkdir /mnt/home/${HOLOUSER}/Desktop
-	cp /etc/holoinstall/steamos-gamemode.desktop /mnt/home/${HOLOUSER}/Desktop/steamos-gamemode.desktop
-	arch-chroot ${HOLO_INSTALL_DIR} chmod +x /home/${HOLOUSER}/Desktop/steamos-gamemode.desktop
 	arch-chroot ${HOLO_INSTALL_DIR} ln -s /usr/share/applications/steam.desktop /home/${HOLOUSER}/Desktop/steam.desktop
 	arch-chroot ${HOLO_INSTALL_DIR} chown -R ${HOLOUSER}:${HOLOUSER} /home/${HOLOUSER}/Desktop
 	arch-chroot ${HOLO_INSTALL_DIR} systemctl enable cups bluetooth sddm holoiso-reboot-tracker
